name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build-scan-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        IMAGE_TAG=${{ github.sha }}
        docker build -t rsakhamuri/cicd-demo:$IMAGE_TAG .
        docker tag rsakhamuri/cicd-demo:$IMAGE_TAG rsakhamuri/cicd-demo:latest

    - name: Scan image with Trivy
      uses: aquasecurity/trivy-action@0.22.0
      with:
        image-ref: rsakhamuri/cicd-demo:${{ github.sha }}
        severity: CRITICAL,HIGH
        exit-code: 1

    - name: Push Docker image
      run: |
        IMAGE_TAG=${{ github.sha }}
        docker push rsakhamuri/cicd-demo:$IMAGE_TAG
        docker push rsakhamuri/cicd-demo:latest

    # ---------- CD STEP ----------
    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          IMAGE_TAG=${{ github.sha }}

          echo "Pulling latest Docker image..."
          docker pull rsakhamuri/cicd-demo:$IMAGE_TAG

          echo "Stopping any container using port 80..."
          docker ps --filter "publish=80" -q | xargs -r docker stop
          docker ps -a --filter "publish=80" -q | xargs -r docker rm

          echo "Stopping existing cicd-app container if exists..."
          docker stop cicd-app || true
          docker rm cicd-app || true


          echo "Starting new container..."
          docker run -d \
          --name cicd-app \
          -p 80:8080 \
          --restart unless-stopped \
          rsakhamuri/cicd-demo:$IMAGE_TAG
